CREATE DATABASE IF NOT EXISTS Bank;
use Bank;
CREATE TABLE IF NOT EXISTS Clients (
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    creditCardNumber VARCHAR(50),
    debitCard VARCHAR(50) NOT NULL,
    accountNumber VARCHAR(50) NOT NULL,
    clientUser VARCHAR(50) NOT NULL,
    clientPassword VARCHAR(10) NOT NULL,
    PRIMARY KEY (id)
	);
    
ALTER TABLE Clients DROP COLUMN fullName;
ALTER TABLE Clients ADD COLUMN fullName VARCHAR(50) NOT NULL;

CREATE TABLE IF NOT EXISTS Areas (
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    areaName VARCHAR(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Employees (
    id INT UNIQUE NOT NULL AUTO_INCREMENT,
    fullName VARCHAR(50) NOT NULL,
    socialSecurityNumber VARCHAR(50) NOT NULL UNIQUE,
    area INT NOT NULL,
    position INT NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Positions (
    id INT NOT NULL UNIQUE AUTO_INCREMENT,
    positionSName VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE Positions RENAME COLUMN positionName TO positionsname;
ALTER TABLE Positions RENAME COLUMN positionsname TO positionName;

CREATE TABLE IF NOT EXISTS DebitCards(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
	cardNumber INT NOT NULL UNIQUE,
    clientsId INT UNIQUE NOT NULL,
    PRIMARY KEY (id, clientsId),
    FOREIGN KEY (clientsId)
    REFERENCES Clients(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

ALTER TABLE Clients DROP COLUMN debitCard;
ALTER TABLE Clients ADD COLUMN debitCard VARCHAR(50) UNIQUE NOT NULL;
ALTER TABLE Clients DROP PRIMARY KEY;
ALTER TABLE Clients ADD PRIMARY KEY (id, debitCardId);
ALTER TABLE Clients ADD FOREIGN KEY debitCardClients(debitCardId) REFERENCES DebitCards(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE Clients MODIFY debitCard VARCHAR(50) UNIQUE;
ALTER TABLE Clients MODIFY debitCardId INT UNIQUE;
ALTER TABLE Clients MODIFY creditCardNumber VARCHAR(50) UNIQUE;

CREATE TABLE IF NOT EXISTS Entities(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
	entityName VARCHAR(50) UNIQUE NOT NULL,
    PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS CreditCards(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
    cardNumber VARCHAR(50) UNIQUE NOT NULL,
    cardLimit INT NOT NULL,
    clientId INT NOT NULL UNIQUE,
    entityId INT NOT NULL UNIQUE,
    PRIMARY KEY(id, clientId, entityId),
    FOREIGN KEY (clientId)
    REFERENCES Clients(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (entityId)
    REFERENCES Entitys(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Banks(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    bankName VARCHAR(50) NOT NULL UNIQUE,
    PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS BankHasClients(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    bankId INT UNIQUE NOT NULL,
    clientsId INT UNIQUE NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (clientsId)
    REFERENCES Clients(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (bankId)
    REFERENCES Banks(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Applicants(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    fullName VARCHAR(50) NOT NULL,
    CV VARCHAR(50) NOT NULL,
    areaId INT UNIQUE NOT NULL,
    positionId INT UNIQUE NOT NULL,
    PRIMARY KEY(id, areaId, positionId),
    FOREIGN KEY (areaId)
    REFERENCES Areas(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (positionId)
    REFERENCES Positions(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS BankHasApplicants(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    applicantId INT UNIQUE NOT NULL,
    bankId INT UNIQUE NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY (applicantId)
    REFERENCES Applicants(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (bankId)
    REFERENCES Banks(id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Taxes(
	id INT NOT NULL UNIQUE AUTO_INCREMENT,
    taxName VARCHAR(50) UNIQUE,
    amount INT NOT NULL,
    PRIMARY KEY(id) 
);

CREATE TABLE IF NOT EXISTS BankHasTaxes(
	id INT UNIQUE NOT NULL AUTO_INCREMENT,
    bankId INT UNIQUE NOT NULL,
    taxId INT NOT NULL UNIQUE,
    FOREIGN KEY (bankId)
    REFERENCES Banks(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    FOREIGN KEY (taxId)
    REFERENCES Taxes(id)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
);